name: Cloud Transfer Workflow

on:

  workflow_dispatch:

    inputs:

      url:

        description: 'Param Url'

        required: true

        default: 'https://raw.githubusercontent.com/ThankRain/cloud_transfer/main/params.txt'    

jobs:

  download:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Set up Python 3.7
       uses: actions/setup-python@v1
       with:
        python-version: 3.7   
     - name: Run Download Script 
       run: |
        pip install requests
        pip install urllib3
        pip install urllib
        python download.py ${{ github.event.inputs.url }}
